// Editor

export const TODO_EDITOR_SET_FORM = "TODO/EDITOR_SET_FORM";

export const TODO_EDITOR_CLOSE_FORM = "TODO/EDITOR_CLOSE_FORM";

// List

export const TODO_LIST_CREATE_NEW = "TODO/LIST_CREATE_NEW";

export const TODO_LIST_UPDATE_TODO = "TODO/LIST_UPDATE_TODO";
